kind: Build
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    openshift.io/build-config.name: blog-django-py-git
    openshift.io/build.number: '1'
    openshift.io/build.pod-name: blog-django-py-git-1-build
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/fiap341865/builds/blog-django-py-git-1
  resourceVersion: '14207417'
  name: blog-django-py-git-1
  uid: ff077b15-1dfd-446f-a7a6-2d17601e1ddb
  creationTimestamp: '2021-12-17T16:58:08Z'
  namespace: fiap341865
  ownerReferences:
    - apiVersion: build.openshift.io/v1
      kind: BuildConfig
      name: blog-django-py-git
      uid: e0ad4a78-29d9-48f9-bfc8-cbb0d4c17146
      controller: true
  labels:
    app: blog-django-py-git
    app.kubernetes.io/part-of: blog-django-py-git-app
    app.kubernetes.io/instance: blog-django-py-git
    openshift.io/build-config.name: blog-django-py-git
    app.kubernetes.io/component: blog-django-py-git
    openshift.io/build.start-policy: Serial
    buildconfig: blog-django-py-git
    app.openshift.io/runtime: python
    app.kubernetes.io/name: python
    app.openshift.io/runtime-version: latest
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'blog-django-py-git:latest'
    pushSecret:
      name: builder-dockercfg-wwtbm
  resources: {}
  triggeredBy:
    - message: Image change
      imageChangeBuild:
        imageID: >-
          image-registry.openshift-image-registry.svc:5000/fiap341865/blog-django-py-git:latest
        fromRef:
          kind: ImageStreamTag
          namespace: openshift
          name: 'python:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: >-
          image-registry.openshift-image-registry.svc:5000/fiap341865/blog-django-py-git:latest
      pullSecret:
        name: builder-dockercfg-wwtbm
  postCommit: {}
  serviceAccount: builder
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift-instruqt/blog-django-py.git'
    contextDir: /
  revision:
    type: Git
    git:
      commit: 9c4f338ab5f3a5ae379ecaa5bcc7d449fa41648e
      author:
        name: ryan jarvinen
        email: ryan.jarvinen@gmail.com
      committer:
        name: GitHub
        email: noreply@github.com
      message: 'Merge pull request #9 from mixpix3ls/master'
status:
  phase: Running
  startTimestamp: '2021-12-17T16:58:08Z'
  outputDockerImageReference: >-
    image-registry.openshift-image-registry.svc:5000/fiap341865/blog-django-py-git:latest
  config:
    kind: BuildConfig
    namespace: fiap341865
    name: blog-django-py-git
  output: {}
  stages:
    - name: FetchInputs
      startTime: '2021-12-17T16:58:11Z'
      durationMilliseconds: 469
      steps:
        - name: FetchGitSource
          startTime: '2021-12-17T16:58:11Z'
          durationMilliseconds: 469
  conditions:
    - type: New
      status: 'False'
      lastUpdateTime: '2021-12-17T16:58:08Z'
      lastTransitionTime: '2021-12-17T16:58:08Z'
    - type: Pending
      status: 'False'
      lastUpdateTime: '2021-12-17T16:58:12Z'
      lastTransitionTime: '2021-12-17T16:58:12Z'
    - type: Running
      status: 'True'
      lastUpdateTime: '2021-12-17T16:58:12Z'
      lastTransitionTime: '2021-12-17T16:58:12Z'
---
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/openshift-instruqt/blog-django-py.git'
    deployment.kubernetes.io/revision: '1'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"blog-django-py-git:latest","namespace":"fiap341865"},"fieldPath":"spec.template.spec.containers[?(@.name==\"blog-django-py-git\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  selfLink: /apis/apps/v1/namespaces/fiap341865/deployments/blog-django-py-git
  resourceVersion: '14207338'
  name: blog-django-py-git
  uid: 473c6959-9239-45e2-a1ef-56fc72a7f5ef
  creationTimestamp: '2021-12-17T16:58:08Z'
  generation: 1
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2021-12-17T16:58:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:app': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
            'f:spec':
              'f:containers':
                'k:{"name":"blog-django-py-git"}':
                  .: {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2021-12-17T16:58:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
          'f:updatedReplicas': {}
  namespace: fiap341865
  labels:
    app: blog-django-py-git
    app.kubernetes.io/component: blog-django-py-git
    app.kubernetes.io/instance: blog-django-py-git
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: blog-django-py-git-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-django-py-git
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blog-django-py-git
        deploymentconfig: blog-django-py-git
    spec:
      containers:
        - name: blog-django-py-git
          image: >-
            image-registry.openshift-image-registry.svc:5000/fiap341865/blog-django-py-git:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  unavailableReplicas: 1
  conditions:
    - type: Available
      status: 'False'
      lastUpdateTime: '2021-12-17T16:58:08Z'
      lastTransitionTime: '2021-12-17T16:58:08Z'
      reason: MinimumReplicasUnavailable
      message: Deployment does not have minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2021-12-17T16:58:08Z'
      lastTransitionTime: '2021-12-17T16:58:08Z'
      reason: ReplicaSetUpdated
      message: ReplicaSet "blog-django-py-git-5885f879f6" is progressing.
